# image will be published to ghcr.io/<user>/<name>
name: rebazzite
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-asus
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-%OS_VERSION%/kylegospo-bazzite-fedora-%OS_VERSION%.repo
    install:
      - corectrl
      - virt-manager
      - firefox
      - firefox-langpacks
      - ryzenadj
      # - kcalc
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - krfb
      - krfb-libs
      - ptyxis
      - waydroid
      - waydroid-selinux
      - xwaylandvideobridge
      - plasma-discover-notifier
      - vim-minimal
      - filelight
      - discover-overlay
  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
       # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - com.vscodium.codium 
      remove:
        - com.obsproject.Studio.Plugin.GStreamerVaapi
        - com.obsproject.Studio.Plugin.Gstreamer
        - com.obsproject.Studio.Plugin.OBSVkCapture
        - org.kde.filelight
        - org.kde.gwenview
        - org.kde.haruna
        - org.kde.okular
    user:
      install:
      remove:
  - type: signing # this sets up the proper policy & signing files for signed images to work fully

